### ISSUE TITLE
Patch for /trunk/dialog-box.h

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gtaubman/doneyet#31]
```
Add comment.
```

Original issue reported on code.google.com by `gtaub...@google.com` on 11 Aug 2011 at 3:43

Attachments:
- [dialog-box.h.patch](https://storage.googleapis.com/google-code-attachments/doneyet/issue-31/comment-0/dialog-box.h.patch)

**Comment by stweise** [comment]
A differently named include guard to serve the same purpose is in place. Will also build all include guards from same name pattern now, making this one obsolete.
