### ISSUE TITLE
Any plans to do a release?

### ISSUE THREAD

**Issue by tuxxy** [gtaubman/doneyet#36]
Hey, there!

Been using this project for a bit now and I love it. Wondering if you intend on doing any releases for it to make it easier to follow along with development so it's easier to update.

**Comment by stweise** [comment]
Hey @tuxxy,

I already introduced versions as tags in git but did not create formal releases from it.
I will have a look into it.

**Comment by stweise** [comment]
tags were not pushed appropriately here, did not spot that.
Release showed up automatically i guess that's all that was needed.

doneyet-1.1.0 can now be found under releases

Let me know if you had something different in mind.
