### ISSUE TITLE
Give doneyet an open source software license

### ISSUE THREAD

**Issue by stweise** [gtaubman/doneyet#39]
I propose giving doneyet an open source software license to be able to work on its contents collaboratively. We should be able to do this without worrying about legal aspects or creating awkward workarounds to protect copyright currently held by @gtaubman.

**Comment by gtaubman** [comment]
Fixed in 037fb1d584fd62cd75756067af8e8adf774cccc8.

**Comment by stweise** [comment]
thanks :-)
